---
version: '3.7'
services:
  mongo:
    container_name: product-service-mongodb
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db
