---
version: '3.7'
services:
  postgres-order-service:
    container_name: postgres-order-service
    image: postgres
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: danny
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always
